env: "dev"
jwtsecretkey: "asdw1qp3ojsmdalcxz"
server:
  port: ":8080"
database:
  host: "localhost"
  port: "5432"
  db_name: "Culina-app"
  db_password: "root"
  db_username: "postgres"
  sslmode: "disable"
typesense:
  host: "http://localhost:8108"
  api_key: "zxc"