version: '3.7'

services:
  backend:
    container_name: server
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - '8080:8080'
    depends_on: 
      - culina-db
      - typesense
    networks:
      - backend
    environment:
      - DB_HOST=culina-db
      - DB_PORT=5432
    volumes:
      - ./backend:/app 

  culina-db:
    container_name: culina-db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Culina-app
    ports: 
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  typesense:
    image: typesense/typesense:27.1
    environment:
      - TYPESENSE_API_KEY=xyz
      - TYPESENSE_DATA_DIR=/data
    ports:
      - "8108:8108"
    volumes:
      - ./data:/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8108/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

volumes:
  postgres_data:

networks:
  backend:
