version: '3.7'

services:

  backend:
    container_name: server
    build: .
    ports: 
      - '8080:8080'
    depends_on: 
      - ciluna-db
    networks:
      - backend

  ciluna-db:
    container_name: ciluna-db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Culina-app
    ports: 
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  typesense:
    image: typesense/typesense:27.1
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'
    networks:
      - backend

volumes:
  postgres_data:
  typesense-data:

networks:
  backend:
